language: cpp
compiler: gcc

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-6
      - g++-6
      - boost1.67

before_script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests --logger=JUNIT
  - ./performance_tests --logger=JUNIT
  - ./integration_tests --logger=JUNIT
  - ./analyzer Analyzer_dir .. 1.0.0
